spring.application.name=procurement-service

server.port=8084

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/procurement_db
spring.datasource.username=root
spring.datasource.password=root

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

services.inventory.url=http://localhost:8083
